HOME_UTIL =	/home/users/util

INCDIR  = -I${HOME_UTIL}

OBJ =	LT2Tool.o \
	MathLinearEquation.o \
	MathLinearEquation2.o \
	MathLinerExquation9.o \
	MathMatrix.o \
	MathMatrixInvese4.o \
	MathMatrixInvese6.o