HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

INCDIR  = -I${HOME_UTIL} \
	-I${HOME_IMAGE}



OBJ =	ImageDitherAll.o \
	ImageDitherErr.o \
	ImageDitherErrExp.o \
	ImageDitherFloyd.o \
	ImageDitherOrd.o \
	ImageDitherPat.o \
	ImageEnhancement.o \
	ImageGrayEnhancement.o
