HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib 

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
EP_LIB = ${HOME_VERSION}/Src/EpLib

AGP_LIB1 = ../../AgpLib
EP_LIB1 = ../../EpLib



INCDIR  = -I${AGP_LIB1} \
          -I${EP_LIB1} \
          -I${AGP_LIB} \
          -I${EP_LIB} \
          -I${HOME_UTIL} -I${HOME_IMAGE} 


OBJ =	EmbedFitBorder.o \
	EmbedFitJnt.o \
	EmbedGapp.o \
	EmbedHunch.o \
	EmbedJntN3.o \
	EmbedLink.o \
	EmbedLinkFinal.o \
	EmbedLinkFit.o \
	EmbedLinkFitCurve.o \
	EmbedMarkBr.o \
	EmbedN3.o \
	EmbedRidge.o \
	EmbedRlLink.o \
	EmbedSegment.o \
	EmbedSelect.o
