HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
AGP_LIB1 = ../../AgpLib



INCDIR  = -I${AGP_LIB1} \
          -I${AGP_LIB} \
          -I${HOME_UTIL}




OBJ =   InfAgp.o \
        InfJnt.o \
        InfHunch.o \
        InfRHnch.o \
        InfRidge.o \
        InfEdge.o \
        InfN3.o \
        InfProfile.o \
        InfBgp.o
