HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
AGP_LIB1 = ../../AgpLib



INCDIR  = -I${AGP_LIB1} \
          -I${AGP_LIB} \
          -I${HOME_UTIL}



OBJ =	FilterAgp.o \
	FilterEdge.o \
	FilterHunch.o \
	FilterLinkLen.o \
	FilterN3.o \
	FilterRh2Hunch.o \
	FilterRidge.o
