HOME_VERSION = /home/users/agp/V11
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib 

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
EP_LIB = ${HOME_VERSION}/Src/EpLib
CODING_LIB = ${HOME_VERSION}/Src/CodingLib
VIMAGE_LIB = ${HOME_VERSION}/Src/VimageLib

AGP_LIB1 = ../../AgpLib
EP_LIB1 = ../../EpLib
CODING_LIB1 = ../../CodingLib



INCDIR  = -I${AGP_LIB1} \
          -I${EP_LIB1} \
          -I${CODING_LIB1} \
          -I${AGP_LIB} \
          -I${EP_LIB} \
          -I${CODING_LIB} \
          -I${VIMAGE_LIB} \
          -I${HOME_UTIL} -I${HOME_IMAGE}



OBJ =	AgpLayer.o \
	AgpLayerBorder.o \
	AgpLayerBox.o \
	AgpLayerClear.o \
	AgpLayerColor.o \
	AgpLayerContourPolylink.o \
	AgpLayerCopy.o \
	AgpLayerCopyContour.o \
	AgpLayerCut.o \
	AgpLayerF.o \
	AgpLayerF1.o \
	AgpLayerFC.o \
	AgpLayerFC1.o \
	AgpLayerFlattening.o \
	AgpLayerFn3.o \
	AgpLayerHole.o \
	AgpLayerInit.o \
	AgpLayerMiddle.o \
	AgpLayerRenumbering.o \
	AgpLayerSelect.o
