HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

INCDIR  = -I${HOME_UTIL} \
	-I${HOME_IMAGE}


OBJ =	GifDecoder.o \
	GifEncoder.o \
	ImageReadGif.o \
	ImageReadGifFrame.o \
	ImageWriteGif.o \
	LzwEncoding.o
