HOME_UTIL =	/home/users/util

INCDIR  = -I${HOME_UTIL} 

OBJ =	GpBuildNumber.o \
	GpByteOrder.o \
	GpDir.o \
	GpFile.o \
	GpFile1.o \
	GpFileName.o \
	GpFunction.o \
	GpIo.o \
	GpMsg.o \
	GpRelinquish.o \
	GpTempFile.o
