HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
CORTRANSFORM_LIB = ${HOME_VERSION}/Src/CorTransformLib 
EP_LIB = ${HOME_VERSION}/Src/EpLib
EXPAND_LIB = ${HOME_VERSION}/Src/ExpandiLib
CODING_LIB = ${HOME_VERSION}/Src/CodingLib
VIMAGE_LIB = ${HOME_VERSION}/Src/VimageLib

AGP_LIB1 = ..
CORTRANSFORM_LIB1 = ../../CorTransformLib
EP_LIB1 = ../../EpLib
EXPAND_LIB1 = ../../ExpandiLib
CODING_LIB1 = ../../CodingLib
VIMAGE_LIB1 = ../../VimageLib



INCDIR  = -I${AGP_LIB1} \
	  -I${CORTRANSFORM_LIB1} \
          -I${EP_LIB1} \
          -I${EXPAND_LIB1} \
	  -I${CODING_LIB1} \
          -I${VIMAGE_LIB1} \
          -I${AGP_LIB} \
	  -I${CORTRANSFORM_LIB} \
          -I${EP_LIB} \
          -I${EXPAND_LIB} \
	  -I${CODING_LIB} \
          -I${VIMAGE_LIB} \
          -I${HOME_UTIL} -I${HOME_IMAGE} 



OBJ =	AgpAddBorder.o \
	AgpAddConstLayer.o \
	AgpAppend.o \
	AgpBgpFill.o \
	AgpBgpFillSmooth.o \
	AgpBgValue.o \
	AgpBrList.o \
	AgpCheckLinkFbr.o \
	AgpCleare.o \
	AgpCloseHole.o \
	AgpConnectJnt.o \
	AgpConst.o \
	AgpCopy.o \
	AgpDelete.o \
	AgpDither.o \
	AgpDitherEdge.o \
	AgpDumpRead.o \
	AgpDumpWrite.o \
	AgpExtend.o \
	AgpFlipH.o \
	AgpFlipV.o \
	AgpImage.o \
	AgpJntBrn4.o \
	AgpLinkLen.o \
	AgpLinkNo.o \
	AgpLinkProf.o \
	AgpMakeUnion.o \
	AgpRepositionLayer.o \
	AgpBgpTest.o \
	AgpMold.o \
	AgpNf.o \
	AgpNormalView.o \
	AgpProfile.o \
	AgpProfileWidth.o \
	AgpScriptRead.o \
	AgpScriptWrite.o \
	AgpUnion.o \
	AgpZoom.o


