HOME_VERSION = /home/users/agp/V11
HOME_UTIL = /home/users/util

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
EP_LIB = ${HOME_VERSION}/Src/EpLib
CODING_LIB = ${HOME_VERSION}/Src/CodingLib

AGP_LIB1 = ../../AgpLib
EP_LIB1 = ../../EpLib
CODING_LIB1 = ../../CodingLib



INCDIR  = -I${AGP_LIB1} \
          -I${EP_LIB1} \
          -I${CODING_LIB1} \
          -I${AGP_LIB} \
          -I${EP_LIB} \
          -I${CODING_LIB} \
          -I${HOME_UTIL}


OBJ =   RlLink.o \
	RlCorner.o \
	RlTool.o \
	RlGapp.o \
	LinkReplace.o
