HOME_UTIL =	/home/users/util

INCDIR  = -I${HOME_UTIL} 

OBJ =	ViewBasePrm.o \
	ViewCamera.o \
	ViewConfig.o \
	ViewCreate.o \
	ViewCreateNormal.o \
	ViewDump.o \
	ViewEulerAngle.o \
	ViewEulerV.o \
	ViewJet.o \
	ViewLoad.o \
	ViewNormal.o \
	ViewObject.o \
	ViewObject1.o \
	ViewPer.o \
	ViewPlane.o \
	ViewPrm.o \
	ViewRoll.o \
	ViewSub.o \
	ViewTool.o
