HOME_UTIL =	/home/users/util

INCDIR  = -I${HOME_UTIL} 

OBJ =	deflate.o \
		trees.o \
		adler32.o \
		zutil.o \
		compress.o \
		inflate.o \
		uncompr.o \
		crc32.o \
		inffast.o \
		inftrees.o \
		zip.o \
		zip_file.o \
		zip_files.o\
		zip_ioapi.o
#		zip_iowin32.o
