HOME_UTIL =	/home/users/util

INCDIR  = -I${HOME_UTIL} 

OBJ =	AppJet2.o \
	CuspJmap23.o \
	DiagonalJet2.o \
	FoldJmap23.o \
	InverseJmap23.o \
	Jet1Tool.o \
	Jet23Array.o \
	Jet23Map.o \
	Jet23Tool.o \
	Jet2Array.o \
	Jet2Inverse.o \
	Jet2Io.o \
	Jet2Map.o \
	Jet2Tool.o