HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

INCDIR  = -I${HOME_UTIL} \
	-I${HOME_IMAGE}


OBJ = 	ImageReadPng.o \
	ImageWritePng.o \
	PngEncoder.o PngDecoder.o \
	png.o  \
	pnggccrd.o  \
	pngread.o  \
	pngset.o  \
	pngwio.o  \
	pngget.o  \
	pngrio.o  \
	pngwrite.o  \
	pngmem.o  \
	pngrtran.o  \
	pngtrans.o  \
	pngwtran.o  \
	pngerror.o  \
	pngpread.o  \
	pngrutil.o  \
	pngvcrd.o  \
	pngwutil.o
