HOME_VERSION = /home/users/agp/V11
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
CODING_LIB = ${HOME_VERSION}/Src/CodingLib
EP_LIB = ${HOME_VERSION}/Src/EpLib

AGP_LIB1 = ../../AgpLib
CODING_LIB1 = ../../CodingLib
EP_LIB1 = ../../EpLib



INCDIR  = -I${AGP_LIB1} \
          -I${CODING_LIB1} \
          -I${EP_LIB1} \
          -I${AGP_LIB} \
          -I${CODING_LIB} \
          -I${EP_LIB} \
          -I${HOME_UTIL} \
          -I${HOME_IMAGE}



OBJ =   TlSelect.o \
	Bezier2Links.o \
	LinkFromLine.o \
	LinkFromGapp.o \
	LinkFilter.o \
	LinkSetProfile.o \
	LinkSplit.o \
	LinkSimplify.o \
	LinkTool2.o \
	LinkClip.o \
	LinkReapproximae.o \
	LinkDistance.o \
	LinkInsidePoint.o \
	LinkBox.o \
	LinkIo.o
