HOME_VERSION = /home/users/agp/V11
HOME_UTIL = /home/users/util

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
EP_LIB = ${HOME_VERSION}/Src/EpLib

AGP_LIB1 = ../../AgpLib
EP_LIB1 = ../../EpLib



INCDIR  = -I${AGP_LIB1} \
	  -I${EP_LIB1} \
          -I${AGP_LIB} \
	  -I${EP_LIB} \
          -I${HOME_UTIL}




OBJ =   RelValue.o  AbsValue.o  \
        SetWidth.o
