HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util

AGP_LIB = ${HOME_VERSION}/Src/AgpLib

AGP_LIB1 = ../../AgpLib



INCDIR  = -I${AGP_LIB1} \
          -I${AGP_LIB} \
          -I${HOME_UTIL}



OBJ =	N3PrimeAgp.o \
	N3PrimeFree.o \
	N3PrimeInNull.o \
	N3PrimeLink.o \
	N3PrimeLoad.o \
	N3PrimeN3ToEdge.o \
	N3PrimeProfile.o
