HOME_VERSION = /home/users/agp/V11
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
EP_LIB = ${HOME_VERSION}/Src/EpLib
EPN_LIB = ${HOME_VERSION}/Src/EpnLib
CODING_LIB = ${HOME_VERSION}/Src/CodingLib



AGP_LIB1 = ../../AgpLib
EP_LIB1 = ../../EpLib
EPN_LIB1 = ../../EpnLib
CODING_LIB1 = ../../CodingLib




INCDIR  = -I${AGP_LIB1} \
			-I${EPN_LIB1} \
			-I${EP_LIB1} \
			-I${CODING_LIB1} \
			-I${AGP_LIB} \
			-I${EPN_LIB} \
			-I${EP_LIB} \
			-I${CODING_LIB} \
			-I${HOME_UTIL}  -I${HOME_IMAGE}



OBJ =	AgpAdaptivePalette.o \
	AgpChangeProfile.o \
	AgpColorF.o \
	AgpColorF1.o \
	AgpColorFN.o \
	AgpGrbRgb.o \
	AgpRgbRange.o \
	AgpRgbY.o \
	AgpRgbYCrCb.o \
	AgpRgbYiq.o \
	AgpRgbYmax.o \
	AgpYCrCbRangeY.o \
	AgpYCrCbRgb.o \
	AgpYiqRgb.o \
	FillAux.o
