HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib

INCDIR  = -I${HOME_UTIL} \
	-I${HOME_IMAGE}

OBJ =	Guasian.o \
	Image.o \
	Image4to1.o \
	Image4Tool.o \
	ImageAdaptivePalette.o \
	ImageAdd.o \
	ImageAlpha.o \
	ImageAux.o \
	ImageAverage.o \
	ImageBackgroundRemoval.o \
	ImageComparison.o \
	ImageConvolution.o \
	ImageCut.o \
	ImageCutUarray.o \
	ImageDifference.o \
	ImageEdgePixel.o \
	ImageEqual.o \
	ImageExtend.o \
	ImageFields.o \
	ImageFile.o \
	ImageHistogram.o \
	ImageHsiTune.o \
	ImageLogo.o \
	ImageNegative.o \
	ImagePreview.o \
	ImagePyramid.o \
	ImageResample.o \
	ImageResize.o \
	ImageRgbYCrCb.o \
	ImageRgbYiq.o \
	ImageSample.o \
	ImageSampleDown.o \
	ImageSampleDownTransparent.o \
	ImageSamplingF.o \
	ImageSline.o \
	ImageSmartPalette.o \
	ImageStretch.o \
	ImageSubtruct.o \
	ImageTransparent.o \
	PaletteTool.o
