HOME_VERSION = /home/users/agp/V9
HOME_UTIL = /home/users/util

AGP_LIB = ${HOME_VERSION}/Src/AgpLib

AGP_LIB1 = ../../AgpLib



INCDIR  = -I${AGP_LIB1} \
          -I${AGP_LIB} \
          -I${HOME_UTIL}



OBJ =   GpTool.o  AgpInsert.o \
	VimFile.o \
    AgpLnf.o AgpClear.o \
    NfAux.o  \
    JntTool.o  JntEdge.o  JntN3.o JntRN3.o  JntN3In.o  \
    N3Tool.o  EdgeTool.o   RidgeTool.o \
    HunchTool.o \
    LinkTool.o LinkTool1.o  LinkIn.o  \
    ProfileTool.o \
    WidthTool.o \
	AdepthTool.o \
	LayerTool.o
