HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib 

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
CORTRANSFORM_LIB = ${HOME_VERSION}/Src/CorTransformLib 
EP_LIB = ${HOME_VERSION}/Src/EpLib
EXPAND_LIB = ${HOME_VERSION}/Src/ExpandLib
CODING_LIB = ${HOME_VERSION}/Src/CodingLib
VIMAGE_LIB = ${HOME_VERSION}/Src/VimageLib

AGP_LIB1 = ../../AgpLib
CORTRANSFORM_LIB1 = ../CorTransformLib
EP_LIB1 = ../../EpLib
EXPAND_LIB1 = ../../ExpandLib
CODING_LIB1 = ../../CodingLib
VIMAGE_LIB1 = ../../VimageLib



INCDIR  = -I${AGP_LIB1} \
	  -I${CORTRANSFORM_LIB1} \
          -I${EP_LIB1} \
          -I${EXPAND_LIB1} \
	  -I${CODING_LIB1} \
          -I${VIMAGE_LIB1} \
          -I${AGP_LIB} \
	  -I${CORTRANSFORM_LIB} \
          -I${EP_LIB} \
          -I${EXPAND_LIB} \
	  -I${CODING_LIB} \
          -I${VIMAGE_LIB} \
          -I${HOME_UTIL} -I${HOME_IMAGE} 



OBJ =	AgpDepthAdd.o \
	AgpDepthDefault.o \
	AgpDepthRange.o \
	AgpDepthSet.o \
	AgpDepthSetBottle.o \
	AgpDepthSetCorner.o \
	AgpDepthSetL.o \
	AgpDepthSmooth0x4.o \
	AgpDepthValue.o
