HOME_VERSION = /home/users/agp/V10
HOME_UTIL = /home/users/util
HOME_IMAGE = /home/users/util/ImageLib 

AGP_LIB = ${HOME_VERSION}/Src/AgpLib
EP_LIB = ${HOME_VERSION}/Src/EpLib

AGP_LIB1 = ../../AgpLib
EP_LIB1 = ../../EpLib



INCDIR  = -I${AGP_LIB1} \
          -I${EP_LIB1} \
          -I${AGP_LIB} \
          -I${EP_LIB} \
          -I${HOME_UTIL} -I${HOME_IMAGE} 


OBJ =	AgpDefaultProfile.o \
	AgpJnt.o \
	AgpJntConnect.o \
	AgpJntCutBrn.o \
	AgpJntEdgeReorder.o \
	AgpJntN3.o \
	AgpJntN3Reposition.o \
	AgpLink2Jnt.o \
	AgpLinkDelete.o \
	AgpLinkFilter.o \
	AgpLinkInverse.o \
	AgpLinkN3rToRidge.o \
	AgpLinkN3ToEdge.o \
	AgpLinkSplit.o \
	AgpPolylinkDelete.o \
	AgpPolylinkInsert.o \
	AgpPolylinkSelect.o \
	AgpProfileLoad.o \
	AgpSelect.o
